n = int(input("Enter a total amount:")):
n_2000 = int(n/2000)
New_amount = (n%2000)
n_500 = int(New_amount/500)
New_amount = (New_amount%500)
n_100 = int(New_amount/100)
New_amount = (New_amount%100)
n_50 = int(New_amount/50)
New_amount = (New_amount%50)
n_20 = int(New_amount/20)
New_amount = (New_amount%20)
n_10 = int(New_amount/10)
New_amount = (New_amount%10)
n_5 = int(New_amount/5)
New_amount = (New_amount%5)
n_2 = int(New_amount/2)
New_amount = (New_amount%2)
n_1 = int(New_amount/1)
New_amount = (New_amount%1)
print("The currency of two thousend %d"%n_2000)
print("The currency of five hundred %d"%n_500)
print("The currency of hundred %d"%n_100)
print("The currency of fifty %d"%n_50)
print("The currency of twenty %d"%n_20)
print("The currency of ten %d"%n_10)
print("The currency of five %d"%n_5)
print("The currency of two %d"%n_2)
print("The currency of one %d"%n_1)
